import numpy as np
import matplotlib.pyplot as plt


# ============================================================
# 1. Static Clutter Removal
# Remove stationary reflections by subtracting the mean
# across the slow-time chirp axis (Axis 1).
# Input shape: (receivers, chirps, range_bins)
# ============================================================

def remove_static_clutter(range_matrix):
    mean_clutter = np.mean(
        range_matrix,
        axis=1,
        keepdims=True
    )

    clean_matrix = range_matrix - mean_clutter

    return clean_matrix


# ============================================================
# 2. Doppler FFT
# Compute FFT across chirps (slow-time Axis 1)
# to obtain Doppler information.
# ============================================================

def doppler_fft(clean_matrix):
    doppler_spectrum = np.fft.fft(
        clean_matrix,
        axis=1
    )

    doppler_spectrum = np.fft.fftshift(
        doppler_spectrum,
        axes=1
    )

    return doppler_spectrum


# ============================================================
# 3. Velocity Axis
# Convert Doppler frequency bins into velocity (m/s).
#
# carrier_frequency:
#     Radar carrier frequency in Hz
#
# chirp_repetition_time:
#     Time between consecutive chirps in seconds
# ============================================================

def calculate_velocity_axis(
    n_chirp,
    chirp_repetition_time,
    carrier_frequency
):
    c = 3e8

    wavelength = c / carrier_frequency

    doppler_frequency = np.fft.fftfreq(
        n_chirp,
        d=chirp_repetition_time
    )

    doppler_frequency = np.fft.fftshift(
        doppler_frequency
    )

    velocity = (wavelength / 2) * doppler_frequency

    return velocity


# ============================================================
# 4. Range-Doppler Map
#
# Input:
#     doppler_spectrum -> (receivers, chirps, range_bins)
#
# Average across receiver antennas (Axis 0)
# Then transpose so that:
#
#     rows    -> Range
#     columns -> Velocity
#
# Final shape:
#     (range_bins, chirps)
# ============================================================

def create_range_doppler_map(doppler_spectrum):

    magnitude = np.abs(doppler_spectrum)

    # Average the receiver antennas
    rdm = np.mean(
        magnitude,
        axis=0
    )

    # Convert:
    # (chirps, range_bins)
    # into:
    # (range_bins, chirps)
    rdm = rdm.T

    return rdm


# ============================================================
# 5. Convert Magnitude to dB
# ============================================================

def magnitude_to_db(data):

    return 20 * np.log10(
        data + 1e-12
    )


# ============================================================
# 6. Plot Range-Doppler Map
#
# X-axis -> Velocity
# Y-axis -> Range
# ============================================================

def plot_range_doppler_map(
    rdm_db,
    velocity,
    range_axis
):

    plt.figure(figsize=(10, 6))

    plt.imshow(
        rdm_db,
        aspect="auto",
        extent=[
            velocity[0],
            velocity[-1],
            range_axis[-1],
            range_axis[0]
        ]
    )

    plt.xlabel("Velocity (m/s)")
    plt.ylabel("Range (m)")
    plt.title("Range-Doppler Map")

    plt.colorbar(
        label="Magnitude (dB)"
    )

    plt.show()


# ============================================================
# 7. Spatial Angle FFT
#
# Compute FFT across receiver antennas (Axis 0)
# to obtain spatial information for azimuth estimation.
# ============================================================

def angle_fft(doppler_spectrum):

    angle_spectrum = np.fft.fft(
        doppler_spectrum,
        axis=0
    )

    angle_spectrum = np.fft.fftshift(
        angle_spectrum,
        axes=0
    )

    return angle_spectrum


# ============================================================
# 8. Main DSP Processing Pipeline
#
# Input:
#     range_matrix:
#         REAL Range Spectrum matrix from Member 2
#         Shape: (receivers, chirps, range_bins)
#
#     range_axis:
#         Range axis generated by Member 2 Range Engine
#
#     chirp_repetition_time:
#         Real chirp repetition time
#
#     carrier_frequency:
#         Real radar carrier frequency
#
# Output:
#     clean_matrix
#     doppler_spectrum
#     velocity
#     rdm
#     rdm_db
#     angle_spectrum
# ============================================================

def process_dsp_and_plot(
    range_matrix,
    range_axis,
    chirp_repetition_time,
    carrier_frequency
):

    # --------------------------------------------------------
    # Step 1: Static Clutter Removal
    # --------------------------------------------------------

    clean_matrix = remove_static_clutter(
        range_matrix
    )


    # --------------------------------------------------------
    # Step 2: Doppler FFT
    # --------------------------------------------------------

    doppler_spectrum = doppler_fft(
        clean_matrix
    )


    # --------------------------------------------------------
    # Step 3: Calculate Velocity Axis
    # --------------------------------------------------------

    n_chirps = range_matrix.shape[1]

    velocity = calculate_velocity_axis(
        n_chirps,
        chirp_repetition_time,
        carrier_frequency
    )


    # --------------------------------------------------------
    # Step 4: Create Range-Doppler Map
    # --------------------------------------------------------

    rdm = create_range_doppler_map(
        doppler_spectrum
    )


    # --------------------------------------------------------
    # Step 5: Convert RDM to dB
    # --------------------------------------------------------

    rdm_db = magnitude_to_db(
        rdm
    )


    # --------------------------------------------------------
    # Step 6: Plot Range-Doppler Map
    # --------------------------------------------------------

    plot_range_doppler_map(
        rdm_db,
        velocity,
        range_axis
    )


    # --------------------------------------------------------
    # Step 7: Spatial Angle FFT
    # --------------------------------------------------------

    angle_spectrum = angle_fft(
        doppler_spectrum
    )


    return (
        clean_matrix,
        doppler_spectrum,
        velocity,
        rdm,
        rdm_db,
        angle_spectrum
    )