startFreqConst_GHz = 77.0             # starting frequency (fc)
bandwidth_GHz =  0.67                 # signal bandwidth (B)
chirpDuration_usec = 60.0             # single chirp per antenna
freqSlopeConst_MHz_usec = 21.0        # slope: MHz/us
numAdcSamples = 128                   # samples
digOutSampleRate = 4000.0             # sampling rate: Ksps
numLoops = 255                        # chirp loops
framePeriodicity_msec =  33.33333    # number of frames per second for real time processing
c=3e8                                 # speed of light